icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
interval = 1
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = " $icon  $utilization.eng(w:4) $frequency"

[[block]]
block = "nvidia_gpu"
interval = 1
format = " \uf4bc GTX 1080 $utilization $clocks $power $temperature"

[[block]]
block = "net"
interval = 1
format = " $icon ^icon_net_up $speed_up.eng(prefix:K,w:4) ^icon_net_down $speed_down.eng(prefix:K,w:4)"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:4) "
format_alt = " $icon_swap $swap_used_percents.eng(w:4) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%Y/%m/%d %R %A') "
